### ISSUE TITLE
Please add capability to rsync from block device to file

### ISSUE THREAD

**Issue by rjanssen2** [WayneD/rsync#296] opened 2022-03-17 12:26 UTC
I have been searching the issues as I expect this to be something that has been suggested before, but I cannot find it.
My request is to add a feature to rsync from a block device to a plain file, to make backups of (snapshots of) of disk volumes.
Is there any particular reason why this is not supported?  I would think that the usual mechanism to rsync files would be working with block devices as well, except that there is no timestamp and no useful filesize, so the checksum method would always have to be used.

**Comment by WayneD** [comment] 2022-03-26 21:21
There is a copy-device patch in the rsync-patches repo that can be used for that, if you like.  I plan to modify it to work using a better internal logic (e.g. it doesn't support a checksum of a device's contents), but it would presumably work for you.  Once I get a better implementation I'll merge it in, probably in the next release cycle.

**Comment by WayneD** [comment] 2022-03-27 22:22
Duplicate of #121.

**Closed by WayneD** 2022-03-27 22:22 UTC
