### ISSUE TITLE
Regression: When run through BackupPC_dump, 3.2.3 dumps file contents in log

### ISSUE THREAD

**Issue by haarp** [WayneD/rsync#95] opened 2020-09-06 15:08 UTC
Hello,

WayneD/rsync@592059c has introduced a bug in combination with BackupPC 3. Dumps work fine until a vanished file is encountered, at which point file data is dumped directly into the log, breaking the backup process.

For reference, in my use case, BackupPC calls rsync on the client device via ssh and this cmdline: `/usr/bin/rsync --server --sender --numeric-ids --perms --owner --group -D --links --hard-links --times --block-size=2048 --recursive --checksum-seed=32761 --ignore-times . /`

I don't understand rsync quite well enough to tell if it's a BackupPC or rsync issue. However,  due to the vast number of BackupPC installs out there that will not receive timely (or any) updates, but still have to backup clients which will receive rsync updates, I'd say that not having such a breaking change in rsync is preferable.

On top of this, it's very difficult to figure out why this breaks BackupPC. It's possible it also breaks other users of rsync. And while `--no-msgs2stderr` can be used to avoid this bug, older rsyncs won't recognize it and abort, prohibiting its widespread use.

Also see backuppc/backuppc#369

Thanks!

**Comment by craigbarratt** [comment] 2020-09-07 05:39
I'm the BackupPC developer.  BackupPC 3.x is very old, and it's quite possible it's broken with the latest rsync.  BackupPC 4.x uses a completely different integration with rsync, and it much more up-to-date with recent and current rsync versions.

Let's work on this issue using the filed BackupPC issue, and we can close or update this issue based on what we find.

**Comment by realtalk69** [comment] 2020-09-08 14:15
Well either way, doesn’t matter at this moment because my is fried. So I won’t be screwing up your projects anymore.

Robert J Collins


On Sep 7, 2020, at 1:39 AM, Craig Barratt <notifications@github.com> wrote:

﻿

I'm the BackupPC developer. BackupPC 3.x is very old, and it's quite possible it's broken with the latest rsync. BackupPC 4.x uses a completely different integration with rsync, and it much more up-to-date with recent and current rsync versions.

Let's work on this issue using the filed BackupPC issue, and we can close or update this issue based on what we find.

**Comment by realtalk69** [comment] 2020-09-08 14:17
My apologies, my computer fried.

Robert J Collins


On Sep 8, 2020, at 10:15 AM, Robert Collins <notifications@github.com> wrote:

﻿

Well either way, doesn’t matter at this moment because my is fried. So I won’t be screwing up your projects anymore.

Robert J Collins


On Sep 7, 2020, at 1:39 AM, Craig Barratt <notifications@github.com> wrote:

﻿

I'm the BackupPC developer. BackupPC 3.x is very old, and it's quite possible it's broken with the latest rsync. BackupPC 4.x uses a completely different integration with rsync, and it much more up-to-date with recent and current rsync versions.

Let's work on this issue using the filed BackupPC issue, and we can close or update this issue based on what we find.

**Comment by craigbarratt** [comment] 2020-09-10 21:33
After checking into this, this change does indeed break BackupPC 3.x.  We confirmed that specifying `--no-msgs2stderr` solves the issue.  Unfortunately that option will fail on an older rsync, and any fix to BackupPC 3.x will take a while to propagate to users, if at all (since packaging support for BackupPC 3.x has atrophied).  BackupPC 3.x still seems in pretty wide use, even though 4.x has been out for a few years.

BackupPC 3.x only uses rsync protocol 28.  Would it be possible to make `--no-msgs2stderr` the default if the protocol is <= 28?  That seems in the spirit of maintaining backward compatibility, and that's so old that it shouldn't affect users who are already using the new options.  If you are ok with that, I'm happy to test that approach to make sure it really fixes the issue.

**Comment by WayneD** [comment] 2020-09-13 01:06
Nobody has specified what the actual rsync issue is.  Completely remove all mention of BackupPC and specify what error behavior is happening.

**Comment by craigbarratt** [comment] 2020-09-25 22:22
Yes, rsync <-> rsync works fine.  This is due to a long-standing bug in the perl module `File::RsyncP` that mishandles stderr from rsync, which was exposed by this change in rsync 3.2.3. (BackupPC 3.x via `File::RsyncP` implements most of rsync protocol 28 and talks directly to rsync.)

I just released a new version 0.76 of `File::RsyncP` on [metacpan](https://metacpan.org/pod/File::RsyncP) that fixes this bug.  Any users with this problem on BackupPC 3.x can fix it by upgrading to this new version.  See the [BackupPC issue 339](https://github.com/backuppc/backuppc/issues/369).

Please go ahead and close this issue.

**Comment by haarp** [comment] 2020-09-26 10:43
IMO, rsync should not enable msgs2stderr by default, at least for rsync protocol 28. Even tho this is not an rsync bug, it will affect users of older `File::RsyncP` that likely will never see updates to that module again.

It's your call tho, @WayneD

**Comment by WayneD** [comment] 2020-09-29 04:51
I'm a bit torn on this one.  I've currently got a potential change in the rsync-patches repo (stderr-compat.diff) that you could try out if you like.

**Comment by craigbarratt** [comment] 2020-10-04 22:51
I tried the patch and confirmed it works fine with both the old (broken) `File::RsyncP` 0.74 and the new fixed one (0.76).

It would be great to include this in the next rsync version, since `File::RsyncP` is so old it's not clear whether or how quickly the fixed version will get packaged and be available in the various distros.  But that's also a reason not to contaminate rsync with this legacy bug unrelated to rsync.

It is completely up to you - I'm fine with telling BackupPC 3.x users that encounter this issue to either upgrade to BackupPC 4.x (which does not use `File::RsyncP`) or upgrade `File::RsyncP` to 0.76.

Thanks for all you do leading rsync development!

**Comment by eLvErDe** [comment] 2021-04-11 11:43
Hello,

I know nobody is supposed to install unstrusted RPMs from Internet, but in case someone trust me and want to do this anyway, here is a zip (because GitHub) containing RHEL7/CentOS 7 SRPM/RPMS on the fixed perl-File-RsyncP package (for the ones having CentOS 7 BackupPC servers):

[perl-File-RsyncP-0.76-1.el7.zip](https://github.com/WayneD/rsync/files/6291621/perl-File-RsyncP-0.76-1.el7.zip)

Just deployed on tested on my servers, confirmed fixing the issue !

Regards, Adam.

**Comment by WayneD** [comment] 2022-01-02 22:49
I've gone ahead an merged in the fix that I worked up in rsync-patches.

**Closed by WayneD** 2022-01-02 22:49 UTC
