### ISSUE TITLE
rsyncd problem after Debian testing upgrade to 3.2.1-1 (from 3.1.3-8)

### ISSUE THREAD

**Issue by gklanderman** [WayneD/rsync#46] opened 2020-07-01 17:00 UTC
First, thank you for a great product, I have been using rsync for
probably 30 years, and my current backup setup for many years without a
problem!

Since Debian pushed 3.2.1 to testing last Friday (6/26), I have been
seeing a problem with rsyncd.. I have 5 modules defined, and since the
update, two are seen as empty directories, while the other three
return the correct contents.

I saw the other crash bug reported which you fixed, but am not seeing a crash.

Here is my rsyncd.conf:

| uid = root
| gid = root
| 
| max verbosity = 6
| 
| max connections = 25
| 
| read only = true
| 
| address = localhost
| port = 17873
| 
| use chroot = true
| 
| 
| [build]
|   path = /build
| 
| [etc]
|   path = /etc
| 
| [home]
|   path = /home
| 
| [music]
|   path = /music
| 
| [root]
|   path = /root

The home and root modules are the ones which appear to be empty.

For example:

% rsync -vvvvvv --port=17873 rsync://localhost/home 
opening tcp connection to localhost port 17873
Connected to localhost (::1)
msg checking charset: ANSI_X3.4-1968
sending daemon args: --server --sender -vvvvvvde.LsfxCIv . home/  (5 args)
(Client) Protocol versions: remote=31, negotiated=31
FILE_STRUCT_LEN=24, EXTRA_LEN=4
receiving file list ... 
server_sender starting pid=36030
[sender] change_dir(/)
[sender] make_file(.,*,0)
[sender] pushing local filters for /
[sender] popping local filters
[sender] flist start=0, used=1, low=0, high=0
[sender] i=0 / ./ mode=040000 len=40 flags=1005
send_file_list done
[sender] flist_eof=1
send_files starting
recv_file_name(.)
received 1 names
done
[Receiver] flist_eof=1
[Receiver] flist start=0, used=1, low=0, high=0
[Receiver] i=0 0 ./ mode=040000 len=40 flags=1005
recv_file_list done
get_local_name count=1 home
generator starting pid=36029
delta-transmission enabled
recv_files(1) starting
recv_generator(.,0)
d---------             40 2020/06/30 22:15:58 .
generate_files phase=1
send_files phase=1
recv_files phase=1
generate_files phase=2
send_files phase=2
send files finished
total: matches=0  hash_hits=0  false_alarms=0 data=0
recv_files phase=2
recv_files finished
generate_files phase=3
generate_files finished

sent 20 bytes  received 508 bytes  1,056.00 bytes/sec
total size is 0  speedup is 0.00
[generator] _exit_cleanup(code=0, file=main.c, line=1779): entered
[generator] _exit_cleanup(code=0, file=main.c, line=1779): about to call exit(0)

however /home is 'drwxr-xr-x' owner/group=root and has three user home directories all
'drwxr-xr-x'.

As an example of one that works:

% rsync -vvvvvv --port=17873 rsync://localhost/build
opening tcp connection to localhost port 17873
Connected to localhost (::1)
msg checking charset: ANSI_X3.4-1968
sending daemon args: --server --sender -vvvvvvde.LsfxCIv . build/  (5 args)
(Client) Protocol versions: remote=31, negotiated=31
FILE_STRUCT_LEN=24, EXTRA_LEN=4
receiving file list ... 
server_sender starting pid=36196
[sender] change_dir(/)
[sender] make_file(.,*,0)
[sender] pushing local filters for /
[sender] make_file(OLDSTUFF,*,2)
[sender] make_file(zsh,*,2)
[sender] make_file(flashplayer,*,2)
[sender] make_file(cddbd,*,2)
[sender] make_file(xemacs,*,2)
[sender] make_file(firefox,*,2)
[sender] make_file(wmctrl,*,2)
[sender] make_file(fvwm,*,2)
[sender] make_file(SOURCE,*,2)
[sender] make_file(xterm,*,2)
[sender] make_file(xv,*,2)
[sender] make_file(fetchmail,*,2)
[sender] popping local filters
[sender] flist start=0, used=13, low=0, high=12
[sender] i=0 / ./ mode=040755 len=4,096 flags=1005
[sender] i=1 / OLDSTUFF/ mode=040755 len=4,096 flags=1000
[sender] i=2 / SOURCE/ mode=040755 len=4,096 flags=1000
[sender] i=3 / cddbd/ mode=040755 len=4,096 flags=1000
[sender] i=4 / fetchmail/ mode=040755 len=4,096 flags=1000
[sender] i=5 / firefox/ mode=040755 len=4,096 flags=1000
[sender] i=6 / flashplayer/ mode=040755 len=4,096 flags=1000
[sender] i=7 / fvwm/ mode=040755 len=4,096 flags=1000
[sender] i=8 / wmctrl/ mode=040755 len=4,096 flags=1000
[sender] i=9 / xemacs/ mode=040755 len=4,096 flags=1000
[sender] i=10 / xterm/ mode=040755 len=4,096 flags=1000
[sender] i=11 / xv/ mode=040755 len=4,096 flags=1000
[sender] i=12 / zsh/ mode=040755 len=4,096 flags=1000
send_file_list done
[sender] flist_eof=1
send_files starting
recv_file_name(.)
recv_file_name(OLDSTUFF)
recv_file_name(zsh)
recv_file_name(flashplayer)
recv_file_name(cddbd)
recv_file_name(xemacs)
recv_file_name(firefox)
recv_file_name(wmctrl)
recv_file_name(fvwm)
recv_file_name(SOURCE)
recv_file_name(xterm)
recv_file_name(xv)
recv_file_name(fetchmail)
received 13 names
done
[Receiver] flist_eof=1
[Receiver] flist start=0, used=13, low=0, high=12
[Receiver] i=0 0 ./ mode=040755 len=4,096 flags=1005
[Receiver] i=1 1 OLDSTUFF/ mode=040755 len=4,096 flags=1000
[Receiver] i=2 1 SOURCE/ mode=040755 len=4,096 flags=1000
[Receiver] i=3 1 cddbd/ mode=040755 len=4,096 flags=1000
[Receiver] i=4 1 fetchmail/ mode=040755 len=4,096 flags=1000
[Receiver] i=5 1 firefox/ mode=040755 len=4,096 flags=1000
[Receiver] i=6 1 flashplayer/ mode=040755 len=4,096 flags=1000
[Receiver] i=7 1 fvwm/ mode=040755 len=4,096 flags=1000
[Receiver] i=8 1 wmctrl/ mode=040755 len=4,096 flags=1000
[Receiver] i=9 1 xemacs/ mode=040755 len=4,096 flags=1000
[Receiver] i=10 1 xterm/ mode=040755 len=4,096 flags=1000
[Receiver] i=11 1 xv/ mode=040755 len=4,096 flags=1000
[Receiver] i=12 1 zsh/ mode=040755 len=4,096 flags=1000
recv_file_list done
get_local_name count=13 build
generator starting pid=36195
delta-transmission enabled
recv_generator(.,0)
recv_files(13) starting
drwxr-xr-x          4,096 2019/12/05 23:34:12 .
recv_generator(OLDSTUFF,1)
drwxr-xr-x          4,096 2018/11/10 16:59:16 OLDSTUFF
recv_generator(SOURCE,2)
drwxr-xr-x          4,096 2019/12/05 23:30:05 SOURCE
recv_generator(cddbd,3)
drwxr-xr-x          4,096 2013/02/17 15:42:56 cddbd
recv_generator(fetchmail,4)
drwxr-xr-x          4,096 2018/11/25 20:00:06 fetchmail
recv_generator(firefox,5)
drwxr-xr-x          4,096 2019/04/11 23:06:41 firefox
recv_generator(flashplayer,6)
drwxr-xr-x          4,096 2019/05/17 14:07:31 flashplayer
recv_generator(fvwm,7)
drwxr-xr-x          4,096 2019/11/21 11:39:18 fvwm
recv_generator(wmctrl,8)
drwxr-xr-x          4,096 2019/12/05 22:59:48 wmctrl
recv_generator(xemacs,9)
drwxr-xr-x          4,096 2013/11/07 17:34:51 xemacs
recv_generator(xterm,10)
drwxr-xr-x          4,096 2019/12/05 23:34:12 xterm
recv_generator(xv,11)
drwxr-xr-x          4,096 2012/12/30 23:57:43 xv
recv_generator(zsh,12)
drwxr-xr-x          4,096 2013/04/10 11:07:24 zsh
generate_files phase=1
send_files phase=1
recv_files phase=1
generate_files phase=2
send_files phase=2
send files finished
total: matches=0  hash_hits=0  false_alarms=0 data=0
recv_files phase=2
recv_files finished
generate_files phase=3
generate_files finished

sent 20 bytes  received 1,904 bytes  3,848.00 bytes/sec
total size is 0  speedup is 0.00
[generator] _exit_cleanup(code=0, file=main.c, line=1779): entered
[generator] _exit_cleanup(code=0, file=main.c, line=1779): about to call exit(0)

Note that /etc also works and has the same permissions, ownership, and
group as /home.

I did not see anything related in the release notes.

thanks for any advice on getting to the bottom of this, I would like
to get my remote backups working again asap.

Greg

**Comment by WayneD** [comment] 2020-07-01 17:48
A new systemd restriction that will be going away soon - Duplicate of #44

**Closed by WayneD** 2020-07-01 17:48 UTC

**Comment by gklanderman** [comment] 2020-07-01 18:14
Thanks for the quick investigation, response, and change for 3.2.2 Wayne!  I didn't even look at bug 44 since I wasn't seeing a chdir failed error.  Cheers!

**Comment by gklanderman** [comment] 2020-07-01 18:25
looks like ProtectHome=read-only makes sense for me.. thanks again

**Comment by gklanderman** [comment] 2020-07-01 23:54
Wayne, can you think of a reason this caused an error in issue #44, but for me rsync (via rsnapshot) happily deleted every file under my backup of /home?

**Comment by gklanderman** [comment] 2020-07-01 23:56
@WayneD sorry should have used proper syntax to ask you a question in previous comment..

**Comment by WayneD** [comment] 2020-07-02 00:50
The systemd change makes the home directories still present (/root/. & /home/$USER/.) but hides all content inside them.  So, your /root module can still cd to /root but not see any content while the other report had a module path down inside a /home/USER/sub/dir/path that was not present.

**Comment by gklanderman** [comment] 2020-07-02 02:06
ahh thank you for explaining.  maybe it would be useful to have an option to error if syncing an empty directory over existing files and one of the --delete options is active?
